version: '3.8'
services:
  arrenda-api:
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/arrendaki
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./:/app
    depends_on:
      - postgres
  postgres:
    image: postgres:12.16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=arrendaki
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: